[package]
name = "wasphax"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
ctor = "0.1.21"
lazy_static = "1.4.0"
libc = "0.2.103"
maplit = "1.0.2"
